name: build
on:
  push:
    branches:
      - master
env:
  # Target stage in docker build
  TARGET: base
  TAG: latest
jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        run: make push
