name: tests
on: push
env:
  # Target stage in docker build
  - TARGET: testing
  - DOCKER_DEFAULT_PLATFORM: linux/arm/v7
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - name: Build test image
        run: docker-compose build backend
      - name: Run tests in image
        run: docker-compose run backend make tests
