name: tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Target stage in docker build
      TARGET: testing
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3
      - name: Run tests in image
        run:
          echo ${ secrets.DOCKER_PWD } | docker login -u ${ secrets.DOCKER_USER } --password-stdin \
          && docker-compose run backend make tests
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      # Target stage in docker build
      TARGET: base
      TAG: latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test image
        run: make push
