name: tests
on: push
env:
  # Target stage in docker build
  TARGET: testing
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: List buildx systems
        run: docker buildx ls
      - name: Build test image
        run: make build-backend
      - name: Run tests in image
        run: docker-compose run backend make tests
